package paketSminkerski;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2019-06-28T23:58:26.400+02:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebService(targetNamespace = "http://www.example.org/SminkerskiSalon/", name = "SminkerskiSalon")
@XmlSeeAlso({ObjectFactory.class})
public interface SminkerskiSalon {

    @WebMethod
    @RequestWrapper(localName = "vratiSveTermineSminkera", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "paketSminkerski.VratiSveTermineSminkera")
    @ResponseWrapper(localName = "vratiSveTermineSminkeraResponse", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "paketSminkerski.VratiSveTermineSminkeraResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<paketSminkerski.TerminType> vratiSveTermineSminkera(
        @WebParam(name = "in", targetNamespace = "")
        int in
    );

    @WebMethod(action = "http://www.example.org/SminkerskiSalon/login")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "paketSminkerski.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "paketSminkerski.LoginResponse")
    @WebResult(name = "out", targetNamespace = "")
    public paketSminkerski.MusterijaType login(
        @WebParam(name = "in", targetNamespace = "")
        paketSminkerski.MusterijaType in
    );

    @WebMethod
    @RequestWrapper(localName = "listaKorisnikovihTermina", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "paketSminkerski.ListaKorisnikovihTermina")
    @ResponseWrapper(localName = "listaKorisnikovihTerminaResponse", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "paketSminkerski.ListaKorisnikovihTerminaResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<paketSminkerski.TerminType> listaKorisnikovihTermina(
        @WebParam(name = "in", targetNamespace = "")
        int in
    );

    @WebMethod
    @RequestWrapper(localName = "vratiSveSminkere", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "paketSminkerski.VratiSveSminkere")
    @ResponseWrapper(localName = "vratiSveSminkereResponse", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "paketSminkerski.VratiSveSminkereResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<paketSminkerski.SminkerType> vratiSveSminkere(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );

    @WebMethod
    @RequestWrapper(localName = "vratiKomentareZaSminkera", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "paketSminkerski.VratiKomentareZaSminkera")
    @ResponseWrapper(localName = "vratiKomentareZaSminkeraResponse", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "paketSminkerski.VratiKomentareZaSminkeraResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<java.lang.String> vratiKomentareZaSminkera(
        @WebParam(name = "in", targetNamespace = "")
        int in
    );

    @WebMethod
    @RequestWrapper(localName = "dodajKomentarNaTermin", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "paketSminkerski.DodajKomentarNaTermin")
    @ResponseWrapper(localName = "dodajKomentarNaTerminResponse", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "paketSminkerski.DodajKomentarNaTerminResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean dodajKomentarNaTermin(
        @WebParam(name = "in", targetNamespace = "")
        paketSminkerski.TerminType in
    );

    @WebMethod
    @RequestWrapper(localName = "zakazi", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "paketSminkerski.Zakazi")
    @ResponseWrapper(localName = "zakaziResponse", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "paketSminkerski.ZakaziResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean zakazi(
        @WebParam(name = "in", targetNamespace = "")
        paketSminkerski.TerminType in
    );
}
