package services1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2019-06-28T23:44:11.728+02:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebService(targetNamespace = "http://www.example.org/SminkerskiSalon/", name = "SminkerskiSalon")
@XmlSeeAlso({ObjectFactory.class})
public interface SminkerskiSalon {

    @WebMethod
    @RequestWrapper(localName = "vratiSveTermineSminkera", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "services1.VratiSveTermineSminkera")
    @ResponseWrapper(localName = "vratiSveTermineSminkeraResponse", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "services1.VratiSveTermineSminkeraResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<services1.TerminType> vratiSveTermineSminkera(
        @WebParam(name = "in", targetNamespace = "")
        int in
    );

    @WebMethod(action = "http://www.example.org/SminkerskiSalon/login")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "services1.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "services1.LoginResponse")
    @WebResult(name = "out", targetNamespace = "")
    public services1.MusterijaType login(
        @WebParam(name = "in", targetNamespace = "")
        services1.MusterijaType in
    );

    @WebMethod
    @RequestWrapper(localName = "listaKorisnikovihTermina", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "services1.ListaKorisnikovihTermina")
    @ResponseWrapper(localName = "listaKorisnikovihTerminaResponse", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "services1.ListaKorisnikovihTerminaResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<services1.TerminType> listaKorisnikovihTermina(
        @WebParam(name = "in", targetNamespace = "")
        int in
    );

    @WebMethod
    @RequestWrapper(localName = "vratiSveSminkere", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "services1.VratiSveSminkere")
    @ResponseWrapper(localName = "vratiSveSminkereResponse", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "services1.VratiSveSminkereResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<services1.SminkerType> vratiSveSminkere(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );

    @WebMethod
    @RequestWrapper(localName = "vratiKomentareZaSminkera", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "services1.VratiKomentareZaSminkera")
    @ResponseWrapper(localName = "vratiKomentareZaSminkeraResponse", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "services1.VratiKomentareZaSminkeraResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<java.lang.String> vratiKomentareZaSminkera(
        @WebParam(name = "in", targetNamespace = "")
        int in
    );

    @WebMethod
    @RequestWrapper(localName = "dodajKomentarNaTermin", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "services1.DodajKomentarNaTermin")
    @ResponseWrapper(localName = "dodajKomentarNaTerminResponse", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "services1.DodajKomentarNaTerminResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean dodajKomentarNaTermin(
        @WebParam(name = "in", targetNamespace = "")
        services1.TerminType in
    );

    @WebMethod
    @RequestWrapper(localName = "zakazi", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "services1.Zakazi")
    @ResponseWrapper(localName = "zakaziResponse", targetNamespace = "http://www.example.org/SminkerskiSalon/", className = "services1.ZakaziResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean zakazi(
        @WebParam(name = "in", targetNamespace = "")
        services1.TerminType in
    );
}
