package services1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2019-06-28T23:44:11.885+02:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebServiceClient(name = "SminkerskiSalon",
                  wsdlLocation = "file:/file:/C:/Users/Miroslav/Desktop/Distribuirani sistemi/WorkspaceDistribuirani/SminkerskiSalon/build/spec/SminkerskiSalon.wsdl",
                  targetNamespace = "http://www.example.org/SminkerskiSalon/")
public class SminkerskiSalon_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/SminkerskiSalon/", "SminkerskiSalon");
    public final static QName SminkerskiSalonSOAP = new QName("http://www.example.org/SminkerskiSalon/", "SminkerskiSalonSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/file:/C:/Users/Miroslav/Desktop/Distribuirani sistemi/WorkspaceDistribuirani/SminkerskiSalon/build/spec/SminkerskiSalon.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SminkerskiSalon_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/file:/C:/Users/Miroslav/Desktop/Distribuirani sistemi/WorkspaceDistribuirani/SminkerskiSalon/build/spec/SminkerskiSalon.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SminkerskiSalon_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SminkerskiSalon_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SminkerskiSalon_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SminkerskiSalon_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SminkerskiSalon_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SminkerskiSalon_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SminkerskiSalon
     */
    @WebEndpoint(name = "SminkerskiSalonSOAP")
    public SminkerskiSalon getSminkerskiSalonSOAP() {
        return super.getPort(SminkerskiSalonSOAP, SminkerskiSalon.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SminkerskiSalon
     */
    @WebEndpoint(name = "SminkerskiSalonSOAP")
    public SminkerskiSalon getSminkerskiSalonSOAP(WebServiceFeature... features) {
        return super.getPort(SminkerskiSalonSOAP, SminkerskiSalon.class, features);
    }

}
