package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2019-06-28T18:14:46.565+02:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebServiceClient(name = "Frizerski",
                  wsdlLocation = "file:/file:/C:/Users/Miroslav/Desktop/Distribuirani sistemi/WorkspaceDistribuirani/FrizerskiSalon/build/spec/Frizerski.wsdl",
                  targetNamespace = "http://www.example.org/Frizerski/")
public class Frizerski_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/Frizerski/", "Frizerski");
    public final static QName FrizerskiSOAP = new QName("http://www.example.org/Frizerski/", "FrizerskiSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/file:/C:/Users/Miroslav/Desktop/Distribuirani sistemi/WorkspaceDistribuirani/FrizerskiSalon/build/spec/Frizerski.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Frizerski_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/file:/C:/Users/Miroslav/Desktop/Distribuirani sistemi/WorkspaceDistribuirani/FrizerskiSalon/build/spec/Frizerski.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Frizerski_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Frizerski_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Frizerski_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Frizerski_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Frizerski_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Frizerski_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Frizerski
     */
    @WebEndpoint(name = "FrizerskiSOAP")
    public Frizerski getFrizerskiSOAP() {
        return super.getPort(FrizerskiSOAP, Frizerski.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Frizerski
     */
    @WebEndpoint(name = "FrizerskiSOAP")
    public Frizerski getFrizerskiSOAP(WebServiceFeature... features) {
        return super.getPort(FrizerskiSOAP, Frizerski.class, features);
    }

}
